services:
  backend:
    build: backend
    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync
          path: backend
          target: /backend
  postgres:
    image: "postgres:13.21-alpine3.20"
    env_file: "backend/.env"
