# Generated by Django 5.2.1 on 2025-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(max_length=5000)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
