# Generated by Django 5.2.1 on 2025-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='country_code',
            field=models.CharField(default='us', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='source_id',
            field=models.CharField(default='bbc-news', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='language_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
