# Generated by Django 5.2.1 on 2025-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_news_country_code_news_source_id_source_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
