# Generated by Django 5.2.1 on 2025-05-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0004_alter_news_source_id_alter_news_source_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source_name',
        ),
    ]
