# Generated by Django 5.2.1 on 2025-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0005_rename_thumbnail_news_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(default='bbc-news', max_length=200),
            preserve_default=False,
        ),
    ]
