# Generated by Django 5.2.1 on 2025-05-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0007_alter_news_source_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='source_url',
            new_name='news_url',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='source_id',
            new_name='source',
        ),
    ]
