# Generated by Django 5.2.1 on 2025-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0009_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
