# Generated by Django 5.2.1 on 2025-05-27 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0010_alter_news_thumbnail_url_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='countries',
            new_name='country_codes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sources',
            new_name='source_ids',
        ),
        migrations.AddField(
            model_name='news',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
