# Generated by Django 5.2.1 on 2025-05-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0011_rename_countries_user_country_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
